---
# Configure cleanup

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ cleanup_services_enable }}"
  when: cleanup_enable_service
