---
# Template configuration files for cleanup

- name: template is copied
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  become: true
  loop: "{{ cleanup_templates_copy }}"
  when: cleanup_copy_templates
